# Generated by Django 5.1.2 on 2024-12-29 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsession',
            name='duration',
        ),
        migrations.AddField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parkingApp.car'),
        ),
        migrations.AddField(
            model_name='payment',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
