# Generated by Django 5.1.2 on 2024-12-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0002_remove_parkingsession_duration_payment_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='session',
            new_name='parking_session',
        ),
    ]
