# Generated by Django 5.1.2 on 2024-12-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0003_parkingsession_duration_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsession',
            name='duration_str',
        ),
    ]
